pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am on the way to build'
            }
        }
        stage('Test') {
            steps {
                echo 'I am testing++++'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying from Github'
            }
        }
        stage('Deploy again') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
        stage('Hello mahesh') {
            steps {
                echo 'Hello mahesh how are you'
            }
        }
        stage('Hello Sasikant') {
            steps {
                echo 'Hello Sasikant, how are you.....'
            }
        }
    }
}
